# Generated by Django 6.1 on 2026-08-29 02:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Consulta',
        ),
    ]
