# Generated by Django 6.1 on 2026-08-29 02:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_delete_consulta'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pet',
            old_name='raça',
            new_name='raca',
        ),
    ]
